export enum EFFECT_TYPES {
  SCARCITY = 'SCARCITY',
  EXCESS = 'ABUNDANCE',
  POVERTY = 'POVERTY',
  ABUNDANCE = 'ABUNDANCE',
  CITY_BUYING_X = 'CITY_BUYING_X',
  CITY_SELLING_X = 'CITY_SELLING_X',
}
